name: Hello AWS
on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  hello-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Say Hello to AWS
        run: echo "Hello, AWS!"